### ISSUE TITLE
Things

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/jsoxhack#1]
- Urls for spotify playlist 
  - spotify:user:benfoxall:playlist:0T43RIJv6CP6DcC1a6HryQ
  - https://open.spotify.com/user/benfoxall/playlist/0T43RIJv6CP6DcC1a6HryQ
- Timings (burrito last order 11, everything else up to you)
- Stub out project list (for prosperity rather than for choosing what to work on)
- Pub location
- Haybrook, Pusher, (Jetbrains? Bamboo?)
- Other stuff

**Comment by benfoxall** [comment]
- Wifi (kind of useless I guess?) "**wo-guest**" / "**Big Society**"

**Comment by benfoxall** [comment]
- code of conduct (I think a link to http://confcodeofconduct.com would be enough for now),  I've put a [slide](https://docs.google.com/presentation/d/1-aIsjCeA1duVCODntU2ZzjpYJ03cfPpiXjTRZqnXZq4/edit#slide=id.gdde0fee9d_1_56) about it in the welcome presentation, so could lift it from that if you want.
- our contact information (probably easier for people to give us a shout, but good to include it just in case)

**Comment by benfoxall** [comment]
- Gitter Link (maybe to the main chat?)

**Comment by spikeheap** [comment]
Donesies
